[package]
name = "keyboard-cleaner-gtk"
version = "0.2.0"
authors = ["gltchitm <42951031+gltchitm@users.noreply.github.com>"]
edition = "2021"

[dependencies]
gio = "0.15.11"
gtk = { version = "0.15.5", features = ["v3_20"] }
gdk = { version = "0.15.4", features = ["v3_20"] }
