[package]
name = "keyboard-cleaner-gtk"
version = "0.1.0"
authors = ["gltchitm <42951031+gltchitm@users.noreply.github.com>"]
edition = "2018"

[dependencies]
gio = "0.9.1"

[dependencies.gtk]
version = "0.9.2"
features = ["v3_20"]

[dependencies.gdk]
version = "0.13.2"
features = ["v3_20"]
